[package]
name = "vulkan-test"
version = "0.1.0"
authors = ["Max Oomen <max@traverseresearch.nl>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gpu-allocator = { path = "../.." }
ash = "0.31"