[package]
name = "gpu-allocator"
version = "0.1.0"
authors = ["Max Oomen <max@traverseresearch.nl>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
ash = "0.31"
backtrace = "0.3"
log = "0.4"
num-traits = "0.2"
thiserror = "1.0"

[workspace]
members = [
    "apps/vulkan-test"
]

[features]
vulkan_device_address = []
